/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.kubsys.keycloak.orely.utils;

import java.util.Objects;

import javax.naming.InvalidNameException;
import javax.naming.ldap.LdapName;
import javax.naming.ldap.Rdn;

import org.jboss.logging.Logger;
import org.keycloak.OAuth2Constants;
import org.keycloak.OAuthErrorException;
import org.keycloak.broker.provider.BrokeredIdentityContext;
import org.keycloak.broker.provider.UserAuthenticationIdentityProvider;
import org.keycloak.broker.provider.UserAuthenticationIdentityProvider.AuthenticationCallback;
import org.keycloak.forms.login.LoginFormsProvider;
import org.keycloak.models.IdentityProviderModel;
import org.keycloak.models.KeycloakSession;
import org.keycloak.sessions.AuthenticationSessionModel;

import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.UriBuilder;

/**
 * A wrapper class for {@link AuthenticationCallback} that intercepts
 * authentication callback events from an external Identity Provider (IdP).
 * <p>
 * This wrapper delegates most operations to the original callback but overrides
 * the {@code error} method to enforce a standard OpenID Connect (OIDC)
 * redirection back to the client application with an {@code access_denied}
 * error, rather than displaying the default Keycloak error page.
 * </p>
 */
public class CallbackWrapper implements UserAuthenticationIdentityProvider.AuthenticationCallback, Constants {

	private static final Logger logger = Logger.getLogger(CallbackWrapper.class);

	private final AuthenticationCallback callback;
	private final KeycloakSession session;

	/**
	 * Constructs a new CallbackWrapper.
	 *
	 * @param callback the original authentication callback to delegate standard
	 *                 operations to
	 * @param session  the current Keycloak session used to retrieve the
	 *                 authentication context
	 */
	public CallbackWrapper(UserAuthenticationIdentityProvider.AuthenticationCallback callback,
			KeycloakSession session) {
		this.callback = callback;
		this.session = session;
	}

	/**
	 * Delegates to the original callback to retrieve and verify the authentication
	 * session.
	 *
	 * @param encodedCode the encoded session code
	 * @return the verified authentication session model
	 */
	@Override
	public AuthenticationSessionModel getAndVerifyAuthenticationSession(String encodedCode) {
		AuthenticationSessionModel authSession = callback.getAndVerifyAuthenticationSession(encodedCode);
		if (authSession != null && authSession.getClient() != null) {
			String homeUrl = authSession.getClient().getBaseUrl();
			if (homeUrl != null && !homeUrl.isBlank()) {
				LoginFormsProvider provider = Objects.requireNonNull(session.getProvider(LoginFormsProvider.class));
				if (provider != null) {
					logger.debugf("Set global redirect URL to %s", homeUrl);
					provider.setAttribute("globalFallbackRedirectUrl", homeUrl);
				}
			}
		}

		return authSession;
	}

	/**
	 * Delegates the successful authentication event to the original callback.
	 *
	 * @param context the context containing the brokered identity information
	 * @return the response generated by the original callback
	 */
	@Override
	public Response authenticated(BrokeredIdentityContext context) {
		String rawNameId = context.getBrokerUserId();
		String idpAliasPrefix = context.getIdpConfig().getAlias() + ".";
		String x500Principal = rawNameId.startsWith(idpAliasPrefix)
				? rawNameId.substring(idpAliasPrefix.length())
				: rawNameId;

		String serialNumber = extractX500Attribute(x500Principal, X500_SERIAL_NUMBER);
		if (serialNumber != null && !serialNumber.isBlank()) {
			context.setId(idpAliasPrefix + serialNumber);
			context.setBrokerUserId(idpAliasPrefix + serialNumber);
			context.setUsername(serialNumber);
			context.setModelUsername(serialNumber);
			if (logger.isDebugEnabled()) {
				logger.debugf("Set Keycloak username to %s", Utils.maskSubjectSerialNumber(context.getUsername()));
			}
		}
		String firstName = extractX500Attribute(x500Principal, X500_GIVENNAME);
		if (firstName != null && !firstName.isBlank()) {
			logger.debugf("Set Keycloak user firstname to %s", Utils.maskName(firstName));
			context.setFirstName(firstName);
		}
		String lastName = extractX500Attribute(x500Principal, X500_SURNAME);
		if (lastName != null && !lastName.isBlank()) {
			logger.debugf("Set Keycloak user lastname to %s", Utils.maskName(lastName));
			context.setLastName(lastName);
		}
		String email = extractX500Attribute(x500Principal, X500_EMAILADDRESS);
		if (email == null || email.isBlank()) {
			email = extractX500Attribute(x500Principal, X500_EMAIL);
			if (email == null || email.isBlank()) {
				email = extractX500Attribute(x500Principal, X500_E);
			}
		}
		if (email != null && !email.isBlank()) {
			logger.debugf("Set Keycloak user email to %s", Utils.maskEmail(email));
			context.setEmail(email);
		}

		return callback.authenticated(context);
	}

	private String extractX500Attribute(String x500Name, String attributeName) {
		try {
			LdapName ldapName = new LdapName(x500Name);
			for (Rdn rdn : ldapName.getRdns()) {
				if (attributeName.equalsIgnoreCase(rdn.getType())) {
					return String.valueOf(rdn.getValue()).trim();
				}
			}
		} catch (InvalidNameException e) {
			throw new IllegalArgumentException("Invalid Principal format: " + x500Name, e);
		}
		return null;
	}

	/**
	 * Delegates the cancellation event to the original callback.
	 *
	 * @param idpConfig the configuration model of the identity provider
	 * @return the response generated by the original callback
	 */
	@Override
	public Response cancelled(IdentityProviderModel idpConfig) {
		return callback.cancelled(idpConfig);
	}

	/**
	 * Delegates the retry login event to the original callback.
	 *
	 * @param identityProvider the identity provider instance
	 * @param authSession      the current authentication session
	 * @return the response generated by the original callback
	 */
	@Override
	public Response retryLogin(UserAuthenticationIdentityProvider<?> identityProvider,
			AuthenticationSessionModel authSession) {
		return callback.retryLogin(identityProvider, authSession);
	}

	/**
	 * Intercepts the error callback from the Identity Provider.
	 * <p>
	 * Instead of relying on the default Keycloak error handling, this method
	 * attempts to retrieve the original client's redirect URI from the
	 * authentication session. If found, it forces an HTTP 302 redirect back to the
	 * client application with standard OIDC error parameters:
	 * {@code error=access_denied} and {@code error_description=[message]}.
	 * </p>
	 * <p>
	 * If the client redirect URI cannot be determined, it falls back to the default
	 * callback error handling.
	 * </p>
	 *
	 * @param idpConfig the configuration model of the identity provider
	 * @param message   the specific error message or code returned by the IdP
	 *                  (e.g., a status message like LTEC_856084)
	 * @return a custom HTTP 302 redirection response, or the default error response
	 *         if the context is missing
	 */
	@Override
	public Response error(IdentityProviderModel idpConfig, String message) {
		AuthenticationSessionModel authSession = session.getContext().getAuthenticationSession();
		if (authSession != null) {
			String redirectUri = authSession.getRedirectUri();
			String state = authSession.getClientNote(OAuth2Constants.STATE);

			if (redirectUri != null) {
				UriBuilder uriBuilder = UriBuilder.fromUri(redirectUri)
						.queryParam(OAuth2Constants.ERROR, OAuthErrorException.ACCESS_DENIED)
						.queryParam(OAuth2Constants.ERROR_DESCRIPTION, message);
				if (state != null) {
					uriBuilder.queryParam(OAuth2Constants.STATE, state);
				}
				return Response.status(Response.Status.FOUND)
						.location(uriBuilder.build())
						.build();
			}
		}

		return callback.error(idpConfig, message);
	}
}