name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Compilation
        run: mvn clean package -DskipTests

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
          generate_release_notes: true
